language: csharp
mono: none
dotnet: 2.0.0

sudo: required
dist: trusty

script:
  - dotnet restore src/NetMQ-unix.sln  
  - dotnet test --filter "Category!=Explicit" -v normal src/NetMQ.Tests/NetMQ.Tests-unix.csproj
